{
  generateTokens=true
  generatePsi=true
  generateStubParser=true

  parserClass="com.siberika.idea.pascal.lang.parser.PascalParser"
  stubParserClass="com.siberika.idea.pascal.lang.parser.PascalParserUtil"

  implements="com.siberika.idea.pascal.lang.psi.PascalPsiElement"
  extends="com.siberika.idea.pascal.lang.psi.impl.PascalPsiElementImpl"

  psiClassPrefix="Pas"
  psiImplClassSuffix="Impl"
  psiPackage="com.siberika.idea.pascal.lang.psi"
  psiImplPackage="com.siberika.idea.pascal.lang.psi.impl"
  psiImplUtilClass="com.siberika.idea.pascal.lang.psi.impl.PascalPsiImplUtil"

  elementTypeHolderClass="com.siberika.idea.pascal.lang.psi.PasTypes"
  elementTypePrefix=""
  elementTypeClass="com.siberika.idea.pascal.lang.psi.PascalPsiElementType"
  tokenTypeClass="com.siberika.idea.pascal.lang.lexer.PascalElementType"

  tokens = [
        COMMENT='regexp:\(\*\w*\*\)'
        STRING_LITERAL="STRING_LITERAL"

        AND="and"
        MOD="mod"
        OR="or"
        IDIV="div"
        SHR="shr"
        SHL="shl"
        IN="in"

        AS="as"
        IS="is"
        NIL="nil"

        CLASS="class"
        DISPINTERFACE="dispinterface"

        TRY="try"
        RAISE="raise"
        EXCEPT="except"
        ON="on"
        FINALLY="finally"

        PROGRAM="program"
        UNIT="unit"
        LIBRARY="library"
        PACKAGE="package"
        USES="uses"
        EXPORTS="exports"
        FINALIZATION="finalization"
        INITIALIZATION="initialization"

        THREADVAR="threadvar"
        ABSOLUTE="absolute"
        OUT="out"
        RESOURCESTRING="resourcestring"
        INLINE="inline"
        PACKED="packed"
        PROPERTY="property"
        ARRAY="array"
        SET="set"
        FILE="file"

        ASM="asm"
        GOTO="goto"
        LABEL="label"
        WITH="with"
        EXIT="exit"
        CONTINUE="continue"
        BREAK="break"

        CONSTRUCTOR="constructor"
        DESTRUCTOR="destructor"
        INHERITED="inherited"
        OBJECT="object"
        OPERATOR="operator"
        REINTRODUCE="reintroduce"
        SELF="self"

        NOT="not"
        XOR="xor"

        TO="to"
        DOWNTO="downto"
        REPEAT="repeat"

        STATIC="static"
        SEALED="sealed"
        FINAL="final"
        HELPER="helper"
        EXPORT="export"
        DISPID="dispid"
        ABSTRACT="abstract"

        STRICT="strict"
        PUBLISHED="published"
        PUBLIC="public"
        PROTECTED="protected"
        PRIVATE="private"
        AUTOMATED="automated"

        MESSAGE="message"
        FORWARD="forward"
        EXTERNAL="external"
        EXPERIMENTAL="experimental"
        DEPRECATED="deprecated"
        ASSEMBLER="assembler"

        INDEX="index"
        DEFAULT="default"

        VIRTUAL="virtual"
        DYNAMIC="dynamic"
        OVERRIDE="override"
        OVERLOAD="overload"

        REGISTER="register"
        STDCALL="stdcall"
        PLATFORM="platform"
        PASCAL="pascal"
        CDECL="cdecl"
        SAFECALL="safecall"

        REFERENCE="reference"

        IMPLEMENTS="implements"
        REQUIRES="requires"
        CONTAINS="contains"

        POINTER="pointer"
        FALSE="false"
        TRUE="true"

        INTERFACE="interface"
        IMPLEMENTATION="implementation"

        VAR="var"
        CONST="const"
        TYPE="type"
        ARRAY="array"
        RECORD="record"
        PROCEDURE="procedure"
        FUNCTION="function"
        OF="of"

        CASE="case"
        BEGIN="begin"
        END="end"
        FOR="for"
        UNTIL="until"
        WHILE="while"
        DO="do"
        IF="if"
        THEN="then"
        ELSE="else"

        READ="read"
        WRITE="write"

        MULT="*"
        PLUS="+"
        MINUS="-"
        DIV="/"
        SEMI=";"
        COMMA=","
        LPAREN="("
        RPAREN=")"
        LBRACK="["
        RBRACK="]"
        EQ="="
        LT="<"
        GT=">"
        GE=">="
        LE="<="
        NE="<>"
        COLON=":"
        ASSIGN=":="
        DOT="."
        DEREF="^"
        AT="@"
        HEXNUM="$"
        CHARNUM="#"
        KEYWORDESCAPE="&"

        INCLUDE="include"
        CT_DEFINE="ct_define"
        CT_UNDEFINE="ct_undefine"
        CT_IFDEF="ct_ifdef"
        CT_IFNDEF="ct_ifndef"
        CT_ELSE="ct_else"
        CT_ENDIF="ct_endif"
        COMP_OPTION="comp_option"

        NAME='regexp:[_\w]\w*'
        RANGE='..'
  ]

  implements(".*QualifiedIdent|NamespaceIdent")="com.siberika.idea.pascal.lang.psi.PascalQualifiedIdent"
  implements(".*ModuleHead|.*Ident|ClassProperty|FormalParameter")="com.siberika.idea.pascal.lang.psi.PascalNamedElement"
  extends(".*ModuleHead|.*Ident|ClassProperty|FormalParameter")="com.siberika.idea.pascal.lang.psi.impl.PascalNamedElementImpl"
  extends("ClassTypeDecl|ObjectDecl|ClassHelperDecl|InterfaceTypeDecl|RecordDecl|RecordHelperDecl")="com.siberika.idea.pascal.lang.psi.impl.PasEntityScopeImpl";
}

//external pascal             ::= parsePascal Module
Module                      ::= moduleUnit | ModuleProgram | moduleLibrary | modulePackage
                            {recoverWhile=recover_main_decl extends="com.siberika.idea.pascal.lang.psi.impl.PascalModuleImpl"
                             implements="com.siberika.idea.pascal.lang.psi.PasEntityScope"}

ModuleProgram               ::= progWithHead | progWoHead
private progWithHead        ::= ProgramModuleHead progWoHead
private progWoHead          ::= [UsesFileClause] BlockGlobal "."

private moduleUnit          ::= UnitModuleHead UnitInterface UnitImplementation "."
UnitModuleHead              ::= UNIT NamespaceIdent HintingDirective* ";" {pin=1}
UsesClause                  ::= USES namespaceNameList {pin=1}

private moduleLibrary       ::= LibraryModuleHead [UsesFileClause] BlockGlobal "." {pin=1}
LibraryModuleHead           ::= LIBRARY NamespaceIdent HintingDirective* ";" {pin=1 recoverWhile=recover_main_decl}

private modulePackage       ::= PackageModuleHead RequiresClause [ContainsClause] END "." {pin=1}
PackageModuleHead           ::= PACKAGE NamespaceIdent ";" {pin=1 recoverWhile=recover_main_decl}
RequiresClause              ::= REQUIRES namespaceNameList {pin=1}
ContainsClause              ::= CONTAINS namespaceFileNameList {pin=1}

UnitInterface               ::= INTERFACE [UsesClause] interfaceDecl* {pin=1 recoverWhile=rec_interface name="interface section"}
private rec_interface       ::= !(IMPLEMENTATION | END)

private interfaceDecl       ::= commonDecl | routineDecl | exportsSection | assemblyAttribute {recoverWhile=recover_decl}
private assemblyAttribute   ::= "[" "assembly" ":" CustomAttributeDecl "]" {pin=2}
private exportsSection      ::= EXPORTS identifier exportItem ("," identifier exportItem)* ";" {pin=1}
private exportItem          ::= ["(" [FormalParameterList] ")"] [INDEX Expression] ["name" Expression] ["resident"]
ExportedRoutine             ::= exportedProc | exportedFunc {extends="com.siberika.idea.pascal.lang.psi.impl.PascalRoutineImpl"}
private exportedFunc        ::= FUNCTION NamedIdent [FormalParameterSection] ":" [CustomAttribute] TypeDecl ";" functionDirective* {pin=1 recoverWhile=recover_decl}
private exportedProc        ::= PROCEDURE NamedIdent [FormalParameterSection] ";" functionDirective* {pin=1 recoverWhile=recover_decl}

private complexType         ::= [PACKED] complexTypePart
private complexTypePart     ::= ClassTypeTypeDecl | structTypeDecl | ArrayType | SetType | FileType
private structTypeDecl      ::= ClassHelperDecl | ClassTypeDecl | InterfaceTypeDecl | ObjectDecl | RecordHelperDecl | RecordDecl

private routineDecl         ::= ExportedRoutine | ClassMethodResolution | ClassMethod
private commonDecl          ::= [CLASS] ClassProperty | ConstSection | TypeSection | [CLASS] VarSection
private structItem          ::= commonDecl | routineDecl | ClassField | Visibility {recoverWhile=recover_classItem}
DeclSection	                ::=	commonDecl | LabelDeclSection | exportsSection | assemblyAttribute {recoverWhile=recover_decl}

UnitImplementation          ::= IMPLEMENTATION [UsesClause] ImplDeclSection unitBlock {pin=1 recoverWhile=recover_impl name="implementation section"}
ImplDeclSection             ::= (MethodImplDecl | RoutineImplDecl | DeclSection)* {recoverWhile=recover_impl}
private unitBlock           ::= UnitInitialization [UnitFinalization] END | CompoundStatement | END {recoverWhile=recover_impl}
UnitInitialization          ::= INITIALIZATION StatementList {pin=1 name="initialization section"}
UnitFinalization            ::= FINALIZATION StatementList  {pin=1 name="finalization section"}

ProgramModuleHead	        ::= PROGRAM NamespaceIdent ProgramParamList? ";" {pin=1 recoverWhile=recover_decl}
ProgramParamList            ::= LPAREN progParam? progParamsRest* RPAREN {pin=1}
private progParamsRest      ::= "," progParam {pin=1}
private progParam           ::= identifier {recoverWhile=recover_progParams}
private recover_progParams  ::= !(',' | ')' | global_decl)

UsesFileClause	            ::=	USES namespaceFileNameList {pin=1 name="uses clause"}
private namespaceFileNameList ::= namespaceFileName namespaceFileNamesRest* ";"
private namespaceFileNamesRest ::= COMMA namespaceFileName {pin=1}
private namespaceFileName	::=	NamespaceIdent [IN quotedString] {recoverWhile=recover_uses_list}
private recover_uses_list   ::= !(',' | global_decl)
private recover_commaList   ::= !(";" | ')' | ',' | ':' | '.' | "]" | DO)

private namespaceNameList   ::= NamespaceIdent namespaceNamesRest* ";"
private namespaceNamesRest  ::= "," NamespaceIdent {pin=1 recoverWhile=recover_uses_list}

private recover_main_decl   ::= !(main_decl)
private recover_decl        ::= !(global_decl | END)

private recover_impl        ::= !(local_decl | END | FINALIZATION | INITIALIZATION)

private local_decl          ::= ';' | '.' | BEGIN | varKey | procKey | constKey | PROPERTY | TYPE | LABEL
private global_decl         ::= local_decl | CONSTRUCTOR | DESTRUCTOR | FINALIZATION | INITIALIZATION
                              | CLASS | EXPORTS | INTERFACE | IMPLEMENTATION | USES | CONTAINS | REQUIRES
private main_decl           ::= local_decl | global_decl | PROGRAM | UNIT | LIBRARY | PACKAGE

private decl_list           ::= ',' | ';' | BEGIN
private recover_var         ::= !(decl_list | identifier | global_decl)
//private recover_const       ::= !(decl_list | Ident)
private recover_type        ::= !(global_decl | identifier '=' | TYPE)

//';' | '.' | BEGIN | VarKey | ProcKey | ConstKey | TYPE | LABEL
//private global_decl        ::= local_decl | FINALIZATION | INITIALIZATION | CLASS | EXPORTS | INTERFACE | IMPLEMENTATION | USES | CONTAINS | REQUIRES

BlockGlobal	                ::=	[';'] DeclSection* BlockBody {pin=2 recoverWhile=recover_declName}
BlockBody	        ::=	CompoundStatement |	AssemblerStatement

AssemblerStatement  ::= ASM assemblerItem* END
private assemblerItem       ::= ',' | '[' | ']' | ':' | '+' | '-' | '*' | '/' | '@' | identifier | NUMBER_INT | NUMBER_HEX | NUMBER_BIN

//private recover_declEnd     ::= BEGIN | TYPE | VarKey | ConstKey | ProcKey | Ident '=' | END
//                              | INITIALIZATION | INTERFACE | IMPLEMENTATION | LABEL

private procKey             ::= FUNCTION | PROCEDURE
RoutineImplDecl             ::= routineDeclHeading ";" functionDirective* ProcBodyBlock
                                {pin=1 recoverWhile=recover_decl name="procedure or function declaration"
                                 extends="com.siberika.idea.pascal.lang.psi.impl.PascalRoutineImpl" implements="com.siberika.idea.pascal.lang.psi.PascalNamedElement"}
MethodImplDecl              ::= methodDeclHeading ";" MethodDirective* [MethodBody]
                                {extends="com.siberika.idea.pascal.lang.psi.impl.PascalRoutineImpl" implements="com.siberika.idea.pascal.lang.psi.PascalNamedElement"}

private routineDeclHeading  ::= funcDecl | procDecl
private methodDeclHeading   ::= funcMethod | procMethod

private funcDecl            ::= [CustomAttribute] FUNCTION  NamedIdent [FormalParameterSection] ":" TypeDecl {pin=2 recoverWhile=recover_decl}
private procDecl            ::= [CustomAttribute] PROCEDURE NamedIdent [FormalParameterSection] {pin=2 recoverWhile=recover_decl}
private procMethod          ::= [CustomAttribute] MethodKey ClassQualifiedIdent [GenericDefinition] [FormalParameterSection] {recoverWhile=recover_decl}
private funcMethod          ::= [CustomAttribute] [CLASS] FUNCTION ClassQualifiedIdent [GenericDefinition] [FormalParameterSection] ":" [CustomAttribute] TypeDecl {recoverWhile=recover_decl}

private functionDirective   ::= overloadDirective | inlineDirectiveSemi | callConventionSemi | oldCallConventionDirectiveSemi | HintingDirective ";" | externalDirective // | "unsafe" ";"
private overloadDirective   ::= OVERLOAD ";"
private oldCallConventionDirectiveSemi ::= oldCallConventionDirective ";"
private oldCallConventionDirective ::= "far" | "local" | "near"
private externalDirective   ::= "varargs" ";" | EXTERNAL ";" | EXTERNAL ConstExpression externalSpecifier* ";"
private externalSpecifier   ::= "name" ConstExpression | INDEX ConstExpression
ProcBodyBlock               ::= ProcForwardDecl | procExternalDecl | BlockGlobal [";"]
private procExternalDecl    ::= EXTERNAL ("name" Expression | INDEX Expression)* functionDirective* {pin=1}
ProcForwardDecl             ::= FORWARD ";" functionDirective* {pin=1}

MethodBody          ::= BlockGlobal ";"
MethodKey           ::= [CLASS] PROCEDURE | CONSTRUCTOR | DESTRUCTOR | CLASS OPERATOR
MethodDirective     ::= REINTRODUCE ';' | OVERLOAD ';' | bindingDirective | abstractDirectiveSemi | inlineDirectiveSemi
                      | callConventionSemi | HintingDirective ";" | dispIDDirective {recoverWhile=recover_classItem}
private dispIDDirective     ::= DISPID Expression ";" {pin=1}
private callConventionSemi  ::= callConvention ";"
private callConvention      ::= CDECL | PASCAL | REGISTER | SAFECALL | STDCALL | EXPORT
private inlineDirectiveSemi ::= inlineDirective ";"
private inlineDirective     ::= INLINE | ASSEMBLER
private abstractDirectiveSemi ::= abstractDirective ";"
private abstractDirective   ::= ABSTRACT | FINAL
private bindingDirective    ::= ((MESSAGE Expression) | STATIC | DYNAMIC | OVERRIDE | VIRTUAL) ";"

LabelDeclSection	        ::=	LABEL label labelsRest* ";" {pin=1 name="label declaration"}
private labelsRest          ::= "," label {recoverWhile=recover_commaList}
private label               ::= identifier | NUMBER_INT | NUMBER_HEX

VarSection	                ::=	varKey varDeclaration+ {pin=1 name="var section"}
private varKey	            ::=	VAR | THREADVAR
private varDeclaration	    ::=	[CustomAttribute] identList ":" TypeDecl [VarValueSpec] HintingDirective* ";" {pin=3 recoverWhile=recover_var}
VarValueSpec	            ::=	ABSOLUTE identifier | ABSOLUTE ConstExpressionOrd | EQ ConstExpression

ConstSection                ::= constKey constDeclaration+ {pin=1 name="const section"}
private constKey            ::= CONST |	RESOURCESTRING
private constDeclaration    ::= [CustomAttribute] NamedIdent [":" TypeDecl] "=" ConstExpression HintingDirective* ";" {pin=2}
NamedIdent                  ::= identifier

TypeSection                 ::= TYPE TypeDeclaration+ {pin=1 name="type section"}
TypeDeclaration             ::= [CustomAttribute] GenericTypeIdent "=" TypeDecl HintingDirective* ";" {pin=3 recoverWhile=recover_type}
GenericTypeIdent    ::= identifier [GenericDefinition]
GenericDefinition   ::= SimpleGenericDefinition | ConstrainedGenericDefinition
SimpleGenericDefinition ::= "<" identifier IdentsRest* ">" {pin=1}
IdentsRest          ::= "," identifier {pin=1}
ConstrainedGenericDefinition ::= "<" ConstrainedGeneric ConstrainedGenericsRest ">" {pin=1}
ConstrainedGeneric  ::= identifier [ ":" GenericConstraint GenericConstraintsRest ]
GenericConstraint   ::= identifier | RECORD | CLASS | CONSTRUCTOR
GenericConstraintsRest ::= "," GenericConstraint {pin=1}
ConstrainedGenericsRest ::= ";" ConstrainedGeneric {pin=1}
GenericPostfix      ::=	"<" TypeDecl TypeDeclsRest* ">" {pin=1}
TypeDeclsRest       ::= "," TypeDecl {pin=1}

private recover_declName        ::= !('(' | ')' | ',' | '.' | ':' | ';' | '[' | ']' | '^' | ':=' | 'add' | 'at'
                                | ABSOLUTE | ASSEMBLER | AUTOMATED | BEGIN | CASE | CDECL | CLASS | CONST | CONSTRUCTOR
                                | DEPRECATED | DESTRUCTOR | DO | DEFAULT | DISPID | DOWNTO | ELSE | END | EXCEPT | EXPERIMENTAL
                                | EXPORT | EXTERNAL | FINALLY | FUNCTION | INDEX | INHERITED | INITIALIZATION | FINALIZATION
                                | INLINE | INTERFACE | IMPLEMENTATION | KEYWORDESCAPE | LABEL | LBRACK | MINUS | NAME
                                | IN | IMPLEMENTS | NOT | NUMBER_HEX | NUMBER_INT | OF | OVERLOAD | PASCAL | PLATFORM | PLUS | PROCEDURE | REGISTER
                                | RESOURCESTRING | RPAREN | SAFECALL | STDCALL | THEN | THREADVAR | TO | TYPE | UNTIL | VAR
                                | PRIVATE | PROPERTY | PROTECTED | PUBLIC | PUBLISHED | RANGE | READ | STRICT | WRITE | USES
                                | CONTAINS | REQUIRES | (identifier "=") | relOp | addOp | mulOp
                                | 'far' | 'local' | 'name' | 'near' | 'nodefault' | 'readonly' | 'remove' | 'stored' | 'varargs' | 'writeonly')

TypeID              ::=	FullyQualifiedIdent

TypeDecl	                ::=	complexType | PointerType | ProcedureType | stringType | variantType | SimpleType | [TYPE] TypeID [GenericPostfix]

ClassField                  ::= field ';' //TODO: remove ";"

ClassTypeDecl               ::= CLASS (classBody | [ClassParent]) {pin=1 name="class declaration"}
private classBody           ::= [ClassState] [ClassParent] structItem* END
ClassHelperDecl             ::= CLASS HELPER [ClassParent] FOR TypeID structItem* END {pin=2 name="class helper declaration"}
InterfaceTypeDecl           ::= interfaceKey [ClassParent] [interfaceGuid] structItem* END
                              | interfaceKey [ClassParent] {pin(".*")=interfaceKey name="interface declaration"}
ObjectDecl                  ::= OBJECT [ClassParent] structItem* END {pin=1 name="object declaration"}
RecordDecl                  ::= RECORD (variantRecord | simpleRecord) END {pin=1 name="record declaration"}
private simpleRecord        ::= recordFieldSemi* structItem*
private variantRecord       ::= recordFieldSemi* recordVariantSection

private recordFieldSemi     ::= ClassField
private field               ::= [CustomAttribute] identList ":" TypeDecl HintingDirective* {pin=3}
RecordFields        ::= [field] (';' field)* [';']  //===***
private recordVariantSection ::= CASE [identifier ":"] TypeDecl OF (recordVariant | ";" )+ {pin=1}
private recordVariant       ::= ConstExpression ("," ConstExpression)* ":" "(" RecordFields ")" {pin=3}

RecordHelperDecl            ::= RECORD HELPER FOR TypeID structItem* END {pin=2}

ClassState          ::= SEALED | ABSTRACT

private recover_classItem   ::= !('[' | identifier
                                | CLASS | CONST | CONSTRUCTOR | DESTRUCTOR | BEGIN | END | FUNCTION | IMPLEMENTS | KEYWORDESCAPE
                                | OPERATOR | PRIVATE | PROCEDURE | PROPERTY | PROTECTED | PUBLIC | PUBLISHED | RESOURCESTRING
                                | STATIC | STRICT | THREADVAR | TYPE | VAR | VIRTUAL)

ClassMethodResolution ::= [CLASS] procKey GenericTypeIdent "." identifier "=" identifier ";"
ClassParent         ::= "(" TypeID ("," TypeID)* ")" {pin=1}

private interfaceGuid       ::= "[" quotedString "]" {pin=1}
private interfaceKey        ::= INTERFACE | DISPINTERFACE

ClassTypeTypeDecl           ::= CLASS OF TypeID {pin(".*")="class of" name="metaclass declaration"}

Visibility                  ::= [STRICT] PRIVATE | [STRICT] PROTECTED | PUBLIC | PUBLISHED | AUTOMATED


ClassMethod         ::= classMethodProc | classMethodFunc {name="method declaration" extends="com.siberika.idea.pascal.lang.psi.impl.PascalRoutineImpl"}
private classMethodProc ::= MethodKey NamedIdent [GenericDefinition] [FormalParameterSection] ";" MethodDirective* {pin=1}
private classMethodFunc ::= [CLASS] FUNCTION NamedIdent [GenericDefinition] [FormalParameterSection] ":" [CustomAttribute] TypeDecl ";" MethodDirective* {pin=2}
ClassProperty ::= [CustomAttribute] [CLASS] PROPERTY NamedIdent [ClassPropertyArray] [":" TypeID] [ClassPropertyIndex] ClassPropertySpecifier* ";" {pin=3}
ClassPropertyArray ::= "[" FormalParameterList "]" {pin=1}
ClassPropertyIndex ::= INDEX ConstExpressionOrd {pin=1}
ClassPropertySpecifier ::= ClassPropertyReadWrite | ClassPropertyDispInterface | "stored" Expression
                                 | DEFAULT Expression | ';' DEFAULT | "nodefault" | IMPLEMENTS TypeID
ClassPropertyReadWrite ::= READ RefNamedIdent | WRITE RefNamedIdent | "add" RefNamedIdent | "remove" RefNamedIdent
RefNamedIdent       ::= identifier
ClassPropertyDispInterface ::= "readonly" ";" | "writeonly" ";" | dispIDDirective

ArrayType           ::= ARRAY [ArrayIndexes] OF ArraySubType {pin=1}
ArrayIndexes ::= "[" [ArrayIndex] ArrayIndexRest* "]" {pin=1}
ArrayIndex          ::= ConstExpressionOrd RANGE ConstExpressionOrd | TypeID     //TODO: TypeID only?
ArrayIndexRest      ::= "," [ArrayIndex] {pin=1}
ArraySubType        ::= CONST | TypeDecl

SetType             ::= SET OF TypeDecl {pin=1}
FileType            ::= FILE [OF TypeDecl] {pin=1}
PointerType         ::= "^" TypeDecl | POINTER {pin=1}

private stringType          ::= "string" ["[" Expression "]"] | TypeID [codePageNumber]
private codePageNumber      ::= "(" ConstExpressionOrd ")" {pin=1}
private variantType         ::= identifier

ProcedureType       ::= MethodType | SimpleProcedureType | ProcedureReference
SimpleProcedureType ::= ProcedureTypeHeading
MethodType          ::= ProcedureTypeHeading OF OBJECT {pin=3}
ProcedureReference  ::= REFERENCE TO ProcedureTypeHeading {pin=1}
ProcedureTypeHeading ::= funcHeading | procHeading;
funcHeading         ::= FUNCTION [FormalParameterSection] ":" [CustomAttribute] TypeDecl {pin=1}
procHeading         ::= PROCEDURE [FormalParameterSection] {pin=1}

SimpleType          ::= identifier | EnumType | SubRangeType
SubRangeType        ::= ConstExpressionOrd [RANGE ConstExpressionOrd]
EnumType            ::= "(" EnumEl EnumRest* ")" {pin=1}
EnumRest            ::= "," EnumEl {pin=1}
EnumEl              ::= identifier ["=" Expression] {recoverWhile=recover_commaList}

CompoundStatement           ::= BEGIN [StatementList] END {pin=1}
StatementList               ::= [statement] statements* {recoverWhile=recover_block}
private statements          ::= ";" [statement] {recoverWhile=recover_statement}
private statement           ::= [LabelId ":" ] statementPart
private statementPart       ::= RepeatStatement | WhileStatement | ForStatement
                              | CaseStatement | WithStatement | RaiseStatement | AssemblerStatement
                              | CompoundStatement | IfStatement | TryStatement | simpleStatement | stmtEmpty
private recover_block ::= !(block_end | block_start)

private simpleStatement     ::= GotoStatement | StmtSimpleOrAssign
StmtSimpleOrAssign          ::= Designator [assignPart]
assignPart                  ::= ":=" (NewStatement | Expression) {pin=1 recoverWhile=recover_statement}
NewStatement                ::= NEW "(" [ Expression ] ("," [ Expression ])* [ "," ConstExpression ] ")"// {pin=1 recoverWhile=recover_statement}
stmtEmpty           ::= //empty

private recover_statement   ::= !(';' | block_end | stmt_start | stmt_middle | block_start | varKey | constKey | TYPE | procKey)

private stmt_start          ::= REPEAT | WHILE | FOR | CASE | WITH | RAISE | IF | TRY | BEGIN | BREAK | CONTINUE | EXIT | GOTO | INHERITED
                              | NUMBER_INT | NUMBER_HEX | NUMBER_REAL | identifier | Ident_kw | KEYWORDESCAPE | '^' | '.' | '[' | '('
private stmt_middle         ::= DO | ELSE | THEN
private block_start         ::= BEGIN | INITIALIZATION | FINALIZATION
private block_end           ::= END | UNTIL | EXCEPT | FINALLY
private after_expr          ::= TO | DO | THEN | OF | DOWNTO | EXCEPT | INDEX | ELSE
                              | "name" | OVERLOAD | inlineDirective | callConvention | oldCallConventionDirective
                              | DEPRECATED | EXPERIMENTAL | PLATFORM | LIBRARY | "varargs" | EXTERNAL | "unsafe"
                              | REINTRODUCE | bindingDirective | abstractDirective | ClassPropertySpecifier

Designator                  ::= //[ "inherited" ] , [ QualifiedIdent | TypeID ] , { DesignatorItem } ===***
                                INHERITED [TypeID] DesignatorItem2? | EntityID DesignatorItemEx* | DesignatorItemEx+

EntityID                    ::= FullyQualifiedIdent
FieldId                     ::= identifier

DesignatorItem      ::= "^" | "." FieldId | "[" ExpressionsList "]"
DesignatorItemEx    ::= DesignatorItem | DesignatorItem2
DesignatorItem2     ::= "(" [ExpressionColon ExpressionColons*] ")"// {pin=1}
ExpressionColon     ::= Expression [ColonConstruct] {recoverWhile=recover_commaList}
ExpressionColons    ::= "," ExpressionColon
ColonConstruct      ::= ":" Expression [ ":" Expression ]

RepeatStatement     ::= REPEAT [StatementList] UNTIL Expression {pin=1}
WhileStatement      ::= WHILE Expression DO statement {pin=1}
ForStatement        ::= FOR Designator (ForCycle | IN) Expression DO statement {pin=1}
ForCycle    ::= ":=" Expression (TO | DOWNTO)

IfStatement                 ::= IF Expression THEN statement [ELSE statement] {pin=1}

CaseStatement       ::= CASE Expression OF CaseItem* [ELSE StatementList [";"] ] END {pin=1}
CaseItem	        ::=	CaseLabel ("," CaseLabel)* ":" statement [";"] {pin=3}
CaseLabel	        ::=	ConstExpressionOrd [RANGE ConstExpressionOrd] //{recoverWhile=recover_commaList}

TryStatement                ::= TRY StatementList (tryExcept | tryFinally) END {pin=1}
private tryFinally          ::= FINALLY StatementList
private tryExcept           ::= EXCEPT HandlerList
HandlerList                 ::= Handler+ [ELSE StatementList] | StatementList
Handler                     ::= ON identifier ":" TypeID "do" statement ";" {pin=1}

WithStatement               ::= WITH Designator designatorsRest* DO statement {pin=1}
private designatorsRest     ::= "," Designator {recoverWhile=recover_commaList}

RaiseStatement              ::= RAISE [Designator] ["at" Designator] {pin=1}

GotoStatement               ::= GOTO LabelId | EXIT [ "(" Expression ")" ] | BREAK | CONTINUE

LabelId                     ::= identifier | NUMBER_INT

SetSection                  ::=	"[" [ExpressionOrd SetRest*] "]"// {pin=1}
SetRest             ::= ("," | RANGE | ) ExpressionOrd //{recoverWhile=recover_commaList}

ClassQualifiedIdent         ::= SubIdent "." SubIdent
FullyQualifiedIdent	        ::=	namespacePart? SubIdent
NamespaceIdent	            ::=	namespacePart? SubIdent
SubIdent                    ::= identifier
private namespacePart       ::= namespaceItem+
private namespaceItem       ::= SubIdent "."// {pin=2 recoverWhile=recover_declName}

HintingDirective            ::= (DEPRECATED [StringFactor]) | EXPERIMENTAL | PLATFORM | LIBRARY// {recoverWhile=recover_hintingDir}
//recover_hintingDir          ::= !(';' | ')' | END | global_decl)

Ident_kw                    ::= OUT | EXIT | BREAK | CONTINUE | OPERATOR | SELF | NEW | REINTRODUCE | OVERLOAD | MESSAGE |STATIC | DYNAMIC
                              | OVERRIDE | VIRTUAL | ABSTRACT | SEALED | FINAL | ASSEMBLER | CDECL | PASCAL | REGISTER | SAFECALL | STDCALL
                              | EXPORT | STRICT | PRIVATE | PROTECTED | PUBLIC | PUBLISHED | AUTOMATED | DISPID | EXTERNAL | FORWARD | HELPER
                              | DEFAULT | IMPLEMENTS | INDEX | READ | WRITE | DEPRECATED | EXPERIMENTAL | PLATFORM | REFERENCE
                              | PACKAGE | CONTAINS | REQUIRES
private identifier          ::= KEYWORDESCAPE ReservedWord | Ident_kw | NAME
ReservedWord	            ::=	NAME //===***
private identList	        ::=	identListItem identListRest*
private identListRest       ::= "," identListItem {pin=1}
private identListItem       ::= NamedIdent {recoverWhile=recover_declName}
//private recover_identList ::= !(')' | ',' | ':' | ';' | '=' | ']')

ConstExpressionOrd          ::=	ExpressionOrd {name="integer constant expression"}
ConstExpression	            ::=	Expression | NewConstExpression | RecordConstExpression {name="constant expression"}
NewConstExpression	        ::=	LPAREN ConstExpression (COMMA ConstExpression)* RPAREN | Expression
RecordConstExpression       ::= Expression | RecordConstValue;
RecordConstValue            ::= "(" recordValue recordValueRest* ")" {pin=1}
private recordValueRest     ::= ";" recordValue
private recordValue         ::= identifier ":" RecordConstExpression

private primary             ::= AT primary | AT AT primary | NOT primary | PLUS primary | MINUS primary
                              | NUMBER_INT | NUMBER_REAL | NUMBER_HEX | NUMBER_BIN | TRUE | FALSE | NIL
                              | "(" Expression ")" | StringFactor | SetSection | Designator

primaryOrd                  ::= NOT primaryOrd | PLUS primaryOrd | MINUS primaryOrd | NUMBER_INT | NUMBER_HEX | TRUE | FALSE | NIL
                              | "(" ExpressionOrd ")" | StringFactor | Designator

private relOp               ::= "<" | ">" | "<=" | ">=" | "<>" | "=" | IN | IS
private addOp               ::=	"+" | "-" | OR | XOR
private mulOp               ::= "*" | "/" | IDIV | MOD | AND | SHL | SHR | AS

Expression ::= ClosureExpression | expr_rel
private expr_rel            ::= expr_sum relOpRest*
private relOpRest           ::= relOp expr_sum {pin=1 recoverWhile=recover_expression}
private expr_sum            ::= expr_product addOpRest*
private addOpRest           ::= addOp expr_product {pin=1 recoverWhile=recover_expression}
private expr_product        ::= primary mulOpRest*
private mulOpRest           ::= mulOp primary {pin=1 recoverWhile=recover_expression}

ExpressionOrd ::= expr_relOrd
private expr_relOrd ::= expr_sumOrd (relOp expr_sumOrd)*
private expr_sumOrd ::= expr_productOrd (addOp expr_productOrd)*
private expr_productOrd ::= primaryOrd (mulOp primaryOrd)*

private recover_expression ::= !(';' | relOp | mulOp | addOp | END | ')' | ',' | ']' | ':' | after_expr)

/*expression ::= factor add_expression * {recoverWhile="expression_recover"}
private factor ::= primary mul_expression *
private primary ::= literal_expression | reference_expression qreference_expression *

left add_expression ::= '+' factor
left mul_expression ::= '*' primary

identifier ::= id
reference_expression ::= identifier {mixin="mypackage.MyReferenceExpressionImpl"}
left qreference_expression ::= '.' identifier {elementType="reference_expression"}

literal_expression ::= number | string*/

ClosureExpression           ::= PROCEDURE [ FormalParameterSection ] BlockGlobal | FUNCTION [ FormalParameterSection ] ":" TypeDecl BlockGlobal
FormalParameterSection      ::= "(" [ FormalParameterList ] ")"
FormalParameterList         ::= FormalParameter (";" FormalParameter)*
FormalParameter             ::= [ CustomAttribute ] [ ParamType ] identList [ ":" TypeDecl ] [ "=" Expression ]
ParamType                    ::= CONST | VAR | OUT | CONSTREF//ParmType


ExpressionsList	            ::= Expression (COMMA Expression)*

CustomAttribute	            ::=	LBRACK CustomAttributeDecl RBRACK | assemblyAttribute
CustomAttributeDecl         ::= FullyQualifiedIdent LPAREN ExpressionsList RPAREN
StringFactor                ::= controlString (quotedString controlString)* [quotedString]
                              | quotedString (controlString quotedString)* [controlString]
private quotedString        ::=	STRING_LITERAL
private controlString       ::=	controlchar+
private controlchar         ::= CHARNUM NUMBER_INT | CHARNUM NUMBER_HEX // ***===
